# Generated by Django 5.2.6 on 2025-09-25 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rasa', models.CharField(blank=True, max_length=50, null=True)),
                ('guna', models.CharField(blank=True, max_length=50, null=True)),
                ('virya', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prakriti', models.CharField(blank=True, choices=[('Vata', 'Vata'), ('Pitta', 'Pitta'), ('Kapha', 'Kapha')], max_length=50, null=True)),
                ('vikriti', models.CharField(blank=True, choices=[('Vata', 'Vata'), ('Pitta', 'Pitta'), ('Kapha', 'Kapha')], max_length=50, null=True)),
                ('agni', models.CharField(blank=True, choices=[('Tikshna', 'Tikshna'), ('Manda', 'Manda'), ('Vishama', 'Vishama'), ('Sama', 'Sama')], max_length=50, null=True)),
                ('health_parameters', models.JSONField(default=dict)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField()),
                ('breakfast', models.JSONField(default=dict)),
                ('lunch', models.JSONField(default=dict)),
                ('dinner', models.JSONField(default=dict)),
                ('full_plan', models.JSONField(default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='diet_planner.patient')),
            ],
        ),
    ]
