# Generated by Django 5.2.6 on 2025-09-25 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietplan',
            options={'ordering': ['-plan_date']},
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='plan_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='rasa',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='virya',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prakriti',
            field=models.CharField(blank=True, choices=[('Vata', 'Vata'), ('Pitta', 'Pitta'), ('Kapha', 'Kapha')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vikriti',
            field=models.CharField(blank=True, choices=[('Vata', 'Vata'), ('Pitta', 'Pitta'), ('Kapha', 'Kapha')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='dietplan',
            index=models.Index(fields=['patient', 'plan_date'], name='diet_planne_patient_fca887_idx'),
        ),
        migrations.AddIndex(
            model_name='dietplan',
            index=models.Index(fields=['-plan_date'], name='diet_planne_plan_da_a33b28_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='diet_planne_name_f6db87_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['rasa', 'virya'], name='diet_planne_rasa_4c307d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['practitioner', 'name'], name='diet_planne_practit_843aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['prakriti'], name='diet_planne_prakrit_deaae2_idx'),
        ),
    ]
