# Generated by Django 5.2.6 on 2025-09-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0002_alter_dietplan_options_alter_dietplan_plan_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('plan_type', models.CharField(choices=[('dosha_balance', 'Dosha Balance'), ('dual_constitution', 'Dual Constitution'), ('therapeutic', 'Therapeutic'), ('seasonal', 'Seasonal'), ('detox', 'Detoxification')], db_index=True, max_length=50)),
                ('target_dosha', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('conditions_treated', models.TextField(blank=True, null=True)),
                ('principle', models.TextField()),
                ('daily_schedule', models.JSONField()),
                ('meal_guidelines', models.JSONField()),
                ('foods_to_favor', models.TextField()),
                ('foods_to_avoid', models.TextField()),
                ('key_points', models.TextField(blank=True, null=True)),
                ('seasonal_adjustments', models.TextField(blank=True, null=True)),
                ('therapeutic_foods', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dietplan',
            name='customizations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='practitioner_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='snacks',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='contraindications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='digestibility',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='kapha_effect',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='pitta_effect',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='seasonal_use',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='therapeutic_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='used_in_plans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vata_effect',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vipaka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='guna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='rasa',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['food_category'], name='diet_planne_food_ca_78961e_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['vata_effect', 'pitta_effect', 'kapha_effect'], name='diet_planne_vata_ef_6832d9_idx'),
        ),
        migrations.AddIndex(
            model_name='dietplantemplate',
            index=models.Index(fields=['plan_type', 'target_dosha'], name='diet_planne_plan_ty_69c378_idx'),
        ),
        migrations.AddIndex(
            model_name='dietplantemplate',
            index=models.Index(fields=['difficulty_level'], name='diet_planne_difficu_8a76df_idx'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet_planner.dietplantemplate'),
        ),
        migrations.AddIndex(
            model_name='dietplan',
            index=models.Index(fields=['is_active'], name='diet_planne_is_acti_247b0e_idx'),
        ),
    ]
