# Generated by Django 5.2.6 on 2025-09-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0003_dietplantemplate_dietplan_customizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='digestibility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='guna',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='kapha_effect',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='pitta_effect',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='rasa',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='seasonal_use',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vata_effect',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vipaka',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='virya',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
